// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestcaseLoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testcaseLogin() {
    driver.Navigate().GoToUrl("http://localhost:3000/UserLogin");
    driver.Manage().Window.Size = new System.Drawing.Size(904, 824);
    driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).SendKeys("s@gmail.com");
    driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).SendKeys("s@12345");
    driver.FindElement(By.CssSelector(".btn")).Click();
  }
}
