// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UserdashboardTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void userdashboard() {
    driver.Navigate().GoToUrl("http://localhost:3000/UserDashboard");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.LinkText("Display user Card")).Click();
    driver.FindElement(By.LinkText("Apply for EMI card")).Click();
    driver.FindElement(By.Name("fullname")).Click();
    driver.FindElement(By.Name("fullname")).SendKeys("Ruban");
    driver.FindElement(By.Name("date_of_birth")).Click();
    driver.FindElement(By.Name("date_of_birth")).SendKeys("2002-03-30");
    driver.FindElement(By.Name("contactNumber")).Click();
    driver.FindElement(By.Name("contactNumber")).SendKeys("9874656123");
    driver.FindElement(By.Name("email_Address")).Click();
    driver.FindElement(By.Name("email_Address")).SendKeys("ruban@gmail.com");
    driver.FindElement(By.Name("current_Address")).Click();
    driver.FindElement(By.Name("current_Address")).SendKeys("kolappalur");
    driver.FindElement(By.Name("permanent_Address")).Click();
    driver.FindElement(By.Name("permanent_Address")).SendKeys("kolappalur");
    driver.FindElement(By.Name("nationality")).Click();
    driver.FindElement(By.Name("nationality")).SendKeys("indian");
    driver.FindElement(By.Name("gender")).Click();
    {
      var dropdown = driver.FindElement(By.Name("gender"));
      dropdown.FindElement(By.XPath("//option[. = 'Male']")).Click();
    }
    driver.FindElement(By.Name("select_card_type")).Click();
    {
      var dropdown = driver.FindElement(By.Name("select_card_type"));
      dropdown.FindElement(By.XPath("//option[. = 'Platinum']")).Click();
    }
    driver.FindElement(By.Name("pan")).Click();
    driver.FindElement(By.Name("pan")).SendKeys("789sdfsd");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("The data has been submitted successfully"));
    driver.FindElement(By.LinkText("purchase Product")).Click();
    driver.FindElement(By.CssSelector(".mt-4:nth-child(2) .btn")).Click();
    driver.FindElement(By.CssSelector(".mt-4:nth-child(4) .btn")).Click();
    driver.FindElement(By.CssSelector(".bg-success:nth-child(5) .nav-link:nth-child(2) > .nav-link")).Click();
    driver.FindElement(By.CssSelector(".card:nth-child(1) .btn")).Click();
    driver.FindElement(By.CssSelector(".btn-warning")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    driver.Close();
  }
}
